// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// Request data to create new user
type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Contains data of created user
type CreateUserResponse struct {
	// ID of created user
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Contains list of all users
type ReadAllUserResponse struct {
	// list of users
	Userlist             []*User  `protobuf:"bytes,1,rep,name=userlist,proto3" json:"userlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllUserResponse) Reset()         { *m = ReadAllUserResponse{} }
func (m *ReadAllUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllUserResponse) ProtoMessage()    {}
func (*ReadAllUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a3086c73a75cdba, []int{3}
}

func (m *ReadAllUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllUserResponse.Unmarshal(m, b)
}
func (m *ReadAllUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllUserResponse.Merge(m, src)
}
func (m *ReadAllUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllUserResponse.Size(m)
}
func (m *ReadAllUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllUserResponse proto.InternalMessageInfo

func (m *ReadAllUserResponse) GetUserlist() []*User {
	if m != nil {
		return m.Userlist
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*CreateUserRequest)(nil), "v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "v1.CreateUserResponse")
	proto.RegisterType((*ReadAllUserResponse)(nil), "v1.ReadAllUserResponse")
}

func init() {
	proto.RegisterFile("user-service.proto", fileDescriptor_2a3086c73a75cdba)
}

var fileDescriptor_2a3086c73a75cdba = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x49, 0x3b, 0xe7, 0xbc, 0x03, 0xc1, 0xab, 0xce, 0x52, 0x7d, 0x28, 0x65, 0x0f, 0x7b,
	0x31, 0xa3, 0xf3, 0x41, 0xd0, 0x17, 0x45, 0xfc, 0x03, 0x15, 0x7f, 0x40, 0x67, 0xaf, 0x23, 0x90,
	0x99, 0x9a, 0xa4, 0x05, 0x5f, 0xfd, 0xe5, 0x92, 0xa4, 0x8a, 0xab, 0xbe, 0x25, 0xe7, 0x9e, 0xfb,
	0xdd, 0xc3, 0x01, 0x6c, 0x0d, 0xe9, 0x4b, 0x43, 0xba, 0x13, 0x2f, 0xc4, 0x1b, 0xad, 0xac, 0xc2,
	0xa8, 0x2b, 0xd2, 0xf3, 0x8d, 0x52, 0x1b, 0x49, 0x4b, 0xaf, 0xac, 0xdb, 0xd7, 0x25, 0x6d, 0x1b,
	0xfb, 0x11, 0x0c, 0xf9, 0x1d, 0x8c, 0x9e, 0x0d, 0x69, 0x3c, 0x84, 0x48, 0xd4, 0x09, 0xcb, 0xd8,
	0x22, 0x2e, 0x23, 0x51, 0x23, 0xc2, 0xc8, 0xe1, 0x92, 0x28, 0x63, 0x8b, 0x83, 0xd2, 0xbf, 0xf1,
	0x04, 0xf6, 0x68, 0x5b, 0x09, 0x99, 0xc4, 0x5e, 0x0c, 0x9f, 0xbc, 0x80, 0xa3, 0x07, 0x4d, 0x95,
	0x25, 0xc7, 0x29, 0xe9, 0xbd, 0x25, 0x63, 0xf1, 0xa2, 0x5f, 0x77, 0xc0, 0xe9, 0x6a, 0xc2, 0xbb,
	0x82, 0xfb, 0xb1, 0x57, 0xf3, 0x39, 0xe0, 0xef, 0x15, 0xd3, 0xa8, 0x37, 0x43, 0xc3, 0x08, 0xf9,
	0x2d, 0x1c, 0x97, 0x54, 0xd5, 0xf7, 0x52, 0xee, 0xd8, 0xe6, 0x30, 0x71, 0x10, 0x29, 0x8c, 0x4d,
	0x58, 0x16, 0xef, 0xe0, 0x7f, 0x26, 0xab, 0x4f, 0x06, 0x53, 0x27, 0x3d, 0x85, 0x3a, 0xf0, 0x1a,
	0xc6, 0xe1, 0x24, 0x9e, 0x3a, 0xf7, 0x9f, 0xc4, 0xe9, 0x6c, 0x28, 0xf7, 0xe7, 0x6e, 0x60, 0xbf,
	0x4f, 0x81, 0x33, 0x1e, 0x9a, 0xe4, 0xdf, 0x4d, 0xf2, 0x47, 0xd7, 0x64, 0x7a, 0xe6, 0x56, 0xff,
	0x89, 0xba, 0x1e, 0x7b, 0xe3, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x2b, 0x29, 0xc6,
	0x9a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// Create new user
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// Read all users
	ReadAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadAllUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadAllUserResponse, error) {
	out := new(ReadAllUserResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// Create new user
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// Read all users
	ReadAll(context.Context, *empty.Empty) (*ReadAllUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) ReadAll(ctx context.Context, req *empty.Empty) (*ReadAllUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _UserService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service.proto",
}
